kind: pipeline
type: docker
name: master

clone:
  disable: true

steps:
- name: clone
  image: smasherofallthings/debug
  commands:
  - GIT_SSL_NO_VERIFY=true git clone -v $DRONE_GIT_HTTP_URL .
  - GIT_SSL_NO_VERIFY=true git checkout $DRONE_COMMIT

- name: Docker Image
  image: smasherofallthings/python-fe:latest
  commands:
  - docker build -t smasherofallthings/weather-exporter:amd64-latest -f Dockerfile.linuxamd64 .
  - docker build -t smasherofallthings/weather-exporter:arm7-latest -f Dockerfile.linuxarm7  .
  - docker manifest create smasherofallthings/weather-exporter:latest --amend smasherofallthings/weather-exporter:amd64-latest --amend smasherofallthings/weather-exporter:amd64-latest
  - docker tag "smasherofallthings/weather-exporter:$$(date '+%Y-%m-%d')-b$${DRONE_BUILD_NUMBER}" smasherofallthings/weather-exporter:latest
  - docker push smasherofallthings/weather-exporter:latest --all-tags
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: docker-creds
    path: /root/.docker/

- name: Push repo to public repos
  image: smasherofallthings/debug
  commands:
  - git checkout $DRONE_BRANCH
  - git remote add github git@github.com:smashthings/weather-exporter.git
  - git push -u github
  - git remote add gitlab git@gitlab.com:scripteddog/weather-exporter.git
  - git push -u gitlab
  volumes:
  - name: ssh-creds
    path: /root/.ssh/

volumes:
- name: docker-socket
  host:
    path: /var/run/docker.sock
- name: docker-creds
  host:
    path: /root/.docker/
- name: ssh-creds
  host:
    path: /root/.ssh/

trigger:
  branch:
    - master
    - pipeline
  event:
    - push
